// utils.js

const axios = require('axios');

// Function to generate content using OpenAI API
async function generateContent(topic) {
  try {
    const response = await axios.post(
      'https://api.openai.com/v1/chat/completions',
      {
        model: 'gpt-4',
        messages: [{ role: 'user', content: `Write an informative LinkedIn article about ${topic}.` }],
      },
      {
        headers: {
          Authorization: `Bearer ${process.env.OPENAI_API_KEY}`,
          'Content-Type': 'application/json',
        },
      }
    );
    
    const content = response.data.choices[0].message.content;
    return content;
  } catch (error) {
    console.error('Error generating content:', error.message);
    throw new Error('Unable to generate content.');
  }
}

// Function to post the generated content to LinkedIn
async function postToLinkedIn(content) {
  try {
    const accessToken = process.env.LINKEDIN_ACCESS_TOKEN;
    const url = 'https://api.linkedin.com/v2/ugcPosts';

    const postData = {
      author: `urn:li:person:YOUR_PERSON_ID`, // Your LinkedIn Person ID
      lifecycleState: 'PUBLISHED',
      specificContent: {
        'com.linkedin.ugc.ShareContent': {
          shareCommentary: {
            text: content, // The article content generated by OpenAI
          },
          shareMediaCategory: 'ARTICLE',
        },
      },
      visibility: {
        'com.linkedin.ugc.MemberNetworkVisibility': 'PUBLIC',
      },
    };

    const response = await axios.post(url, postData, {
      headers: {
        Authorization: `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
        'X-Restli-Protocol-Version': '2.0.0',
      },
    });

    console.log('Article successfully posted to LinkedIn');
    return response.data;
  } catch (error) {
    console.error('Error posting to LinkedIn:', error.message);
    throw new Error('Unable to post to LinkedIn.');
  }
}

module.exports = { generateContent, postToLinkedIn };
